### ISSUE TITLE
check-mongodb.py:46: syntax error

### ISSUE THREAD

**Issue by runningman84** [sensu-plugins/sensu-plugins-mongodb#20]
Something seems to be wrong with the current script:
```
/opt/sensu/embedded/bin/check-mongodb.py:23:in `load': /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-plugins-mongodb-0.0.7/bin/check-mongodb.py:46: syntax error, unexpected ':', expecting end-of-input (SyntaxError)
```

**Comment by runningman84** [comment]
hmm this problem should have been fixed here?

https://github.com/sensu-plugins/sensu-plugins-mongodb/issues/6

**Comment by law** [comment]
I am also experiencing this.

**Comment by chilladx** [comment]
+1

Note that it actually works if you directly call the python script: `/opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-plugins-mongodb-0.0.7/bin/check-mongodb.py`

**Comment by eheydrick** [comment]
The issue is that you can't execute non-ruby binstubs. To work around this we've supplied ruby wrappers for the python scripts (see https://github.com/sensu-plugins/sensu-plugins-mongodb/blob/master/bin/check-mongodb.rb). We're in the process of moving the build pipeline over to Travis and haven't released a version with the wrapper yet but when the release is cut you'll be able to run the plugin from the bin directory. In the meantime you could use the workaround suggested by @chilladx or locally build the plugin from master.

**Comment by eheydrick** [comment]
Version 0.0.8 includes a ruby wrapper script for check-mongodb.py.
