### ISSUE TITLE
OK returned when querying unknown host

### ISSUE THREAD

**Issue by 030** [sensu-plugins/sensu-plugins-mongodb#30]
- clone the repo
- ./sensu-plugins-mongodb/bin/check-mongodb.rb -H bla results in OK - Connection took 0 seconds and the exitcode is 0

Expected outcome

exitcode 2

**Comment by ninjada** [comment]
seeing the same, plugin is returning OK even when mongod is not running.

**Comment by 030** [comment]
The default does not seem to  work:

```
def check_connect(host, port, warning, critical, perf_data, user, passwd, conn_time):
    warning = warning or 3
    critical = critical or 6
    message = "Connection took %i seconds" % conn_time
    message += performance_data(perf_data, [(conn_time, "connection_time", warning, critical)])

    return check_levels(conn_time, warning, critical, message)
```

Could someone explain how this could be fixed?

**Comment by luukholleman** [comment]
This is still the case if someone is wondering. Any updates on a fix?

**Comment by luukholleman** [comment]
Can confirm that this is the problem.

Adding `con.admin.command('ismaster')` to line 290 makes it work again. It fails after a long time because the default timeouts are 30 & 20 seconds. 

Adding connectTimeoutMS=1000, serverSelectionTimeoutMS=1000 to the connection will make the check fail in 1 second. I have no idea how to write/run ruby tests so I can't make a PR.

**Comment by walruz** [comment]
Welp, noticed that this is isn't working while my cluster was down for maintenance and no alarms were being triggered. Why is this still an issue? Is there anything we can do to fix it?

**Comment by majormoses** [comment]
Im open to a pr which it looks like adding the following will fix: https://github.com/sensu-plugins/sensu-plugins-mongodb/issues/30#issuecomment-279354082

**Comment by majormoses** [comment]
> Why is this still an issue? Is there anything we can do to fix it?

@walruz  Simply because no one has submitted a PR despite the known fix laid out in the comment above.  Yes you can absolutely fix it as I would welcome any sane PR that improves the quality of the plugins  especially when it fixes real users problems. Sensu plugins are community driven and the vast majority of new plugins and contributions come from the community and not maintainers or even Sensu employees. While yes it's true to become a maintainer you must first become a contributor, there are 170+ plugins with very specialized knowledge on many of them and expecting us to solve every problem that happens across all of them with a small group (15 if you include a bot) of maintainers in our free time is not reasonable. The majority of maintainers do not work for Sensu nor do we get compensated by Sensu to work on this project. When we have time we fix issues + add features, but a maintainers role is primarily to moderate questions, contributions, and do releases.

If I do not see a contribution shortly I will take a look at fixing this myself but I would like to see if someone is willing to spend the time to fix and test it as I don't really run mongo in my environments and a real world test case would be much better.

**Comment by majormoses** [comment]
Well I had some free time and I think I got this working: https://github.com/sensu-plugins/sensu-plugins-mongodb/pull/44 can someone who is actually running mongodb make sure that this does not cause issues? I have validated it should fail if there is no mongo listening on the specified host.

**Comment by majormoses** [comment]
Got a mongo instance to test against:
```
$ ./bin/check-mongodb.rb --host 10.55.150.42 --port 27000
OK - Connection took 0 seconds
```

Would like to see if we can get someone with proper SSL and auth setup to verify it does not falsely swallow any errors there.

**Comment by majormoses** [comment]
OK I have done a few tests and feel fairly confident that this should work. If I don't get a review by sometime on monday I will merge and release a hotfix.

**Comment by majormoses** [comment]
I have released: https://rubygems.org/gems/sensu-plugins-mongodb/versions/1.2.2 which should resolve the issue please feel free to message here if it is still not resolved for you and I can re-open.
